#!/usr/bin/env python3
"""Validate the offline capability catalog and generate its Markdown view."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "offline-capabilities.json"
OUTPUT = ROOT / "docs" / "OFFLINE_PARITY.md"
STATUSES = ("Complete", "Partial", "Planned", "Excluded", "Blocked")
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:[.-][a-z0-9]+)*$")
REQUIRED_STRINGS = (
    "id",
    "area",
    "title",
    "phase",
    "status",
    "acceptance",
    "testFixtureOwner",
    "budget",
    "limits",
)


def fail(message: str) -> None:
    raise ValueError(message)


def validate(catalog: dict) -> list[dict]:
    if catalog.get("schemaVersion") != 1:
        fail("schemaVersion must be 1")
    capabilities = catalog.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities:
        fail("capabilities must be a non-empty array")

    seen: set[str] = set()
    for index, capability in enumerate(capabilities):
        label = f"capabilities[{index}]"
        if not isinstance(capability, dict):
            fail(f"{label} must be an object")
        for field in REQUIRED_STRINGS:
            value = capability.get(field)
            if not isinstance(value, str) or not value.strip():
                fail(f"{label}.{field} must be a non-empty string")
        capability_id = capability["id"]
        if not ID_PATTERN.fullmatch(capability_id):
            fail(f"{capability_id}: invalid stable ID")
        if capability_id in seen:
            fail(f"{capability_id}: duplicate stable ID")
        seen.add(capability_id)
        if capability["status"] not in STATUSES:
            fail(f"{capability_id}: unknown status {capability['status']}")
        for field in ("dependencies", "evidence"):
            value = capability.get(field)
            if not isinstance(value, list) or not all(
                isinstance(item, str) and item.strip() for item in value
            ):
                fail(f"{capability_id}.{field} must be an array of strings")
        if capability["status"] in ("Complete", "Partial") and not capability["evidence"]:
            fail(f"{capability_id}: {capability['status']} requires evidence")
        for evidence in capability["evidence"]:
            relative_path, separator, symbol = evidence.partition("#")
            evidence_path = ROOT / relative_path
            if not evidence_path.is_file():
                fail(f"{capability_id}: missing evidence path {relative_path}")
            if separator:
                if not symbol:
                    fail(f"{capability_id}: empty evidence symbol in {evidence}")
                contents = evidence_path.read_text(encoding="utf-8")
                if symbol not in contents:
                    fail(f"{capability_id}: missing evidence symbol {evidence}")
    return capabilities


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(catalog: dict, capabilities: list[dict]) -> str:
    counts = Counter(item["status"] for item in capabilities)
    lines = [
        "<!-- Generated by scripts/generate_offline_parity.py; do not edit. -->",
        "# Offline capability catalog",
        "",
        cell(catalog["scope"]),
        "",
        "This is an evidence backlog, not a product-parity claim. Stable IDs are never",
        "reused; status changes and evidence changes must update the source catalog in the",
        "same commit.",
        "",
        "## Counts",
        "",
        "| Complete | Partial | Planned | Excluded | Blocked | Total |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
        f"| {counts['Complete']} | {counts['Partial']} | {counts['Planned']} | "
        f"{counts['Excluded']} | {counts['Blocked']} | {len(capabilities)} |",
        "",
        "## Status rules",
        "",
    ]
    for status in STATUSES:
        lines.append(f"- **{status}** — {cell(catalog['statusDefinitions'][status])}")
    lines += [
        "",
        "## Capabilities",
        "",
        "| Stable ID | Area | Capability | Status | Phase | Acceptance recipe | Test/fixture owner | Dependencies | Budget | Evidence | Exclusions or limits |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in sorted(capabilities, key=lambda value: (value["area"], value["id"])):
        dependencies = ", ".join(item["dependencies"]) or "None"
        evidence = ", ".join(f"`{entry}`" for entry in item["evidence"]) or "None yet"
        lines.append(
            "| "
            + " | ".join(
                cell(value)
                for value in (
                    f"`{item['id']}`",
                    item["area"],
                    item["title"],
                    item["status"],
                    item["phase"],
                    item["acceptance"],
                    item["testFixtureOwner"],
                    dependencies,
                    item["budget"],
                    evidence,
                    item["limits"],
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
        capabilities = validate(catalog)
        generated = render(catalog, capabilities)
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"offline parity validation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except OSError as error:
            print(f"offline parity drift: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                "offline parity drift: run scripts/generate_offline_parity.py",
                file=sys.stderr,
            )
            return 1
    else:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")

    counts = Counter(item["status"] for item in capabilities)
    print(
        "offline parity: "
        + ", ".join(f"{status}={counts[status]}" for status in STATUSES)
        + f", Total={len(capabilities)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
